"""test env db load

Revision ID: 892957ff58c0
Revises: 748a131a2415
Create Date: 2025-11-27 09:07:25.817872

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "892957ff58c0"
down_revision: Union[str, Sequence[str], None] = "748a131a2415"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
